name: s-cofi-pl
channels:
  - conda-forge
dependencies:
  - python=3.10.14
  - numpy
  - scipy
  - autograd
  - jax
  - jaxopt
  - time
  - pymanopt
  - joblib
  - sys
  - os
  - argparse
  - tqdm
  - matplotlib
  - pip
  - ipython
  - pip:
    - pyyaml